# This file defines the Rust style for automatic reformatting.
# See also https://rust-lang.github.io/rustfmt
#
# ANGLE's rustfmt file mostly follows Chromium's, with the exception of line widths.

# Rust language edition to be used by the parser.
edition = "2024"
# Version of the formatting rules to use.
style_edition = "2024"
# Line endings will be converted to \n.
newline_style = "Unix"
wrap_comments = true
comment_width = 100
max_width = 100
# The "Default" setting has a heuristic which splits lines too aggresively.
# We are willing to revisit this setting in future versions of rustfmt.
# Bugs:
# * https://github.com/rust-lang/rustfmt/issues/3119
# * https://github.com/rust-lang/rustfmt/issues/3120
use_small_heuristics = "Max"
