name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        arch: [ "arm64" ]
      fail-fast: false

    name: "Build for Android ${{matrix.arch}}"
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Get ANGLE
        uses: actions/checkout@v4
        with:
          path: 'angle'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      - name: Build ANGLE
        shell: bash
        run: |
          git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
          export PATH=`pwd`/depot_tools:$PATH
          echo $PATH
          cd angle
          python scripts/bootstrap.py
          gclient sync
          gn gen out/Android-${{matrix.arch}}
          autoninja -C out/Android-${{matrix.arch}}
      - name: Upload ANGLE
        uses: actions/upload-artifact@v4
        with:
          name: angle-libs-${{matrix.arch}}
          path: |
            angle/out/Android-${{matrix.arch}}/ï¼Š.so
